# Numpy

Numpy is like list but with more features and faster.


List is a collection of data objects. 
Example: [1,2,3,4,5,6,7,8,9,10]

A list can contain a diferent type of data objects.

Example: [1,2,3,4,5,6,7,8,9,10, "Hello", "World"]

Otherwise NumPy array can contain only one type of data objects.

Example: [1,2,3,4,5,6,7,8,9,10] or [1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10] or ["Hello", "World"]


## How to import numpy?

In [38]:
import numpy as np

Its common to import numpy as np

It's possible to use list to create a numpy array or tuple.

#### What's array?

Array is a collection of data objects of the same type.

In [39]:
using_list = np.array([1, 2, 3, 4, 5])
print(using_list)

using_tuple = np.array((1, 2, 3, 4, 5))
print(using_tuple)


[1 2 3 4 5]
[1 2 3 4 5]


Let's check the type of the using_list and using_tuple.

In [40]:
display(f'The type of using_list is {type(using_list)}, and the type of using_tuple is {type(using_tuple)}')

"The type of using_list is <class 'numpy.ndarray'>, and the type of using_tuple is <class 'numpy.ndarray'>"

They are equal?

In [41]:
type(using_list) == type(using_tuple)

True

Yes they are equal!

Let's check out now the data type using dtype.

In [42]:
display(f'The data type of using_list is {using_list.dtype}, and the data type of using_tuple is {using_tuple.dtype}')

'The data type of using_list is int64, and the data type of using_tuple is int64'

They are int64. In other words, they are integers.

It's possible to declare the data type in creation time. Let's check out.

In [43]:
declaring_int_for_list = np.array([1, 2, 3, 4, 5], dtype='int')

declaring_float_for_tuple = np.array((1, 2, 3, 4, 5), dtype='float')

display(f'The data type of declaring_int_for_list is {declaring_int_for_list.dtype}, and the data type of declaring_float_for_tuple is {declaring_float_for_tuple.dtype}')

'The data type of declaring_int_for_list is int64, and the data type of declaring_float_for_tuple is float64'

As we see we have an integer declaration and a float declaration. Are they equal?

In [44]:
print(f'The datatype of list are equal? {declaring_int_for_list.dtype == declaring_float_for_tuple.dtype}. \n' 
f'The type of list are equal? {type(declaring_int_for_list) == type(declaring_float_for_tuple)}')


The datatype of list are equal? False. 
The type of list are equal? True


The data type is different. The first one is int64 and the second one is float64. But the type of the array is the same.

Let's look at dimensions.

In [45]:
one_dimensional_array = np.array([1, 2, 3, 4, 5])

One Dimensional Array only needs one index to access the data object. If we want the first element we use the index 0. If we want the value 3 we use the index 2.

### How we check the dimension of an array?

We use the attribute ndim.

In [46]:
print(f'The number of dimensions is: {one_dimensional_array.ndim}')

The number of dimensions is: 1


In [47]:
two_dimensional_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(f'The number of dimensions is: {two_dimensional_array.ndim}')

The number of dimensions is: 2


Look at the variable ```two_dimensional_array```, we have a list of lists.

So for two dimensional array we need two indexes to access the data object. We can access the value 1 using: ```two_dimensional_array[0][0]```

The arrays can´t contain diferent sizes. For example ```two_dimensional_array_with_diferent_size = np.array([[1,2,3], [2,4,5,6]])```

In [48]:
three_dimensional_array = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(f'The number of dimensions is: {three_dimensional_array.ndim}')

# To access an element:

print(f'To access an value, for example 17: three_dimensional_array[1][1][1]')

The number of dimensions is: 3
To access an value, for example 17: three_dimensional_array[1][1][1]


To avoid confusion you need to check the '[]' where it start and where it ends, for example, ```[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]] ``` This are at index 0. We know that because the first declarition of '[]' Ends at the end of the List. And the seccond declaration of '[]' Starts in sequence of the first declaration of '[]' and ends at the end of the seccond list. So the third '[]' represents the first list.

Another example. If we want to access the value 3. We can use: ```three_dimensional_array[0][0][2]```

After every '[]' the containts gets more specific.

We can use for loops to access the data objects.

### What's shape? 

the shape is the number of elements in each dimension. We can use the attribute shape to check it out.

For example the shape of ```three_dimensional_array``` is (2, 2, 5). It means that we have 2 elements in the first dimension, 2 elements in the seccond dimension and 3 elements in the third dimension.

The shape starts with the less specific dimension and ends with the most specific dimension. For example the value 5 represents the amount of elements in the third dimension.

In [49]:
# One dimensional array: one_dimensional_array = np.array([1, 2, 3, 4, 5])
# Two dimensional array: two_dimensional_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Three dimensional array: three_dimensional_array = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(f'The shape of one_dimensional_array is: {one_dimensional_array.shape}')
print(f'The shape of two_dimensional_array is: {two_dimensional_array.shape}')
print(f'The shape of three_dimensional_array is: {three_dimensional_array.shape}')

The shape of one_dimensional_array is: (5,)
The shape of two_dimensional_array is: (2, 5)
The shape of three_dimensional_array is: (2, 2, 5)


After know about shape, we can use that knowledge to use for loops to access the data objects. Let's check out.

In [50]:
num_rows, num_cols = two_dimensional_array.shape

for i in range(num_rows):
    for j in range(num_cols):
        element = two_dimensional_array[i, j]
        print(f"Element at row {i}, column {j}: {element}")

Element at row 0, column 0: 1
Element at row 0, column 1: 2
Element at row 0, column 2: 3
Element at row 0, column 3: 4
Element at row 0, column 4: 5
Element at row 1, column 0: 6
Element at row 1, column 1: 7
Element at row 1, column 2: 8
Element at row 1, column 3: 9
Element at row 1, column 4: 10


In [51]:
num_rows, num_cols , depth = three_dimensional_array.shape

for i in range(num_rows):
    for j in range(num_cols):
        for k in range(depth):
            element = three_dimensional_array[i, j, k]
            print(f"Element at row {i}, column {j}, depth {k}: {element}")

Element at row 0, column 0, depth 0: 1
Element at row 0, column 0, depth 1: 2
Element at row 0, column 0, depth 2: 3
Element at row 0, column 0, depth 3: 4
Element at row 0, column 0, depth 4: 5
Element at row 0, column 1, depth 0: 6
Element at row 0, column 1, depth 1: 7
Element at row 0, column 1, depth 2: 8
Element at row 0, column 1, depth 3: 9
Element at row 0, column 1, depth 4: 10
Element at row 1, column 0, depth 0: 11
Element at row 1, column 0, depth 1: 12
Element at row 1, column 0, depth 2: 13
Element at row 1, column 0, depth 3: 14
Element at row 1, column 0, depth 4: 15
Element at row 1, column 1, depth 0: 16
Element at row 1, column 1, depth 1: 17
Element at row 1, column 1, depth 2: 18
Element at row 1, column 1, depth 3: 19
Element at row 1, column 1, depth 4: 20


Looking at that we can see that the amount of dimensions is equal to the amount of for loops. In other words, more dimensions equals a more algorithms complexity.

The foor loop is useful if we are in doubt about how to access a data object.

### What's size?

The size is the total number of elements in the array. We can use the attribute size to check it out.

In [52]:
print(f'The amount of elements in three_dimensional_array is: {three_dimensional_array.size}')

The amount of elements in three_dimensional_array is: 20


### npRange

#### What's npRange?

npRange is a function that creates an array with a range of numbers.

#### How to use npRange?

We can use npRange to create an array with a range of numbers. For example, ```np.arange(0, 10)``` creates an array with a range of numbers from 0 to 9.

#### What's the difference between npRange and range?

The difference is that npRange creates an array and range creates a list.



In [53]:
arrange_example = np.arange(0, 10)
arrange_example

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
print(f'The shape of arrange_example is: {arrange_example.shape},  the dimension is: {arrange_example.ndim}, and the size is: {arrange_example.size}')

The shape of arrange_example is: (10,),  the dimension is: 1, and the size is: 10


We can start at any number. For example, ```np.arange(1, 10)``` creates an array with a range of numbers from 1 to 9.

In [55]:
any_start = np.arange(66, 100)
any_start

array([66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

It's possible to use a step. For example, ```np.arange(1, 10, 2)``` creates an array with a range of numbers from 1 to 9 with a step of 2.

In [56]:
any_step = np.arange(0, 100, 5)
any_step

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

### Permutations

#### What's permutations?

Permutation is a function to shuffle the elements of an array.

#### How to use permutations?

We can use permutations to shuffle the elements of an array. For example, ```np.random.permutation(np.arange(0, 10))``` shuffles the elements of an array with a range of numbers from 0 to 9.


In [57]:
permutation_example = np.random.permutation(np.arange(0, 10))
permutation_example

array([1, 0, 8, 7, 5, 4, 3, 9, 6, 2])

Every time we re-run the code the elements are shuffled in a different way.

#### Whatś randint?

radint is a function to generate random integers.

#### How to use radint?

We can use radint to generate random integers. For example, ```np.random.randint(0, 10)``` generates a random integer from 0 to 9.

In [58]:
radint_example1 = np.random.randint(0,10)
radint_example1

8

If we generate only one value, the type of the data object is an integer.

In [59]:
type_check = np.random.randint(0,10)
print(f'The type of type_check is: {type(type_check)}')

The type of type_check is: <class 'int'>


We can add a 'size' parameter to generate more than one random integer. For example, ```np.random.randint(0, 10, size=10)``` generates 10 random integers from 0 to 9.

In [60]:
radint_size_example = np.random.randint(0,10, size=10)

print(f'The type of variable is: {type(radint_size_example)}\nThe shape of radint_size_example is: {radint_size_example.shape},  the dimension is: {radint_size_example.ndim}, and the size is: {radint_size_example.size}\nThe array is: {radint_size_example}')

The type of variable is: <class 'numpy.ndarray'>
The shape of radint_size_example is: (10,),  the dimension is: 1, and the size is: 10
The array is: [1 8 3 9 8 7 6 7 6 3]


Look, using the radint function we generate a array, and we can define the number of dimensions usign the 'size' parameter. For example, ```np.random.randint(0, 10, size=(2, 2, 5))``` generates a array with 2 elements in the first dimension, 2 elements in the seccond dimension and 3 elements in the third dimension.

In [61]:
radint_example = np.random.randint(0, 10, size=(2,2,5))
print(f'The type of variable is: {type(radint_example)}\nThe shape of radint_example is: {radint_example.shape},  the dimension is: {radint_example.ndim}, and the size is: {radint_example.size}\nThe array is: {radint_example}')

The type of variable is: <class 'numpy.ndarray'>
The shape of radint_example is: (2, 2, 5),  the dimension is: 3, and the size is: 20
The array is: [[[3 6 5 3 6]
  [1 2 8 3 8]]

 [[5 6 6 3 9]
  [6 2 6 0 4]]]


### Rand

The rand function generates random numbers between 0 and 1.

In [62]:
A = np.random.rand(10)

### Randn

The randn function generates random numbers between -1 and 1.

In [63]:
gauss_distribution = np.random.randn(10)
gauss_distribution

array([-0.27126379, -0.19208559,  0.0958911 ,  0.25787259, -1.59575268,
        0.72763555, -0.40318597, -0.40036584,  0.2791767 , -0.69316855])

### Shape and Reshape

#### What's reshape?

reshape is a function to change the shape of an array.

#### How to use reshape?

We can use reshape to change the shape of an array. For example, ```np.arange(0, 10).reshape(2, 5)``` changes the shape of an array with a range of numbers from 0 to 9 to a array with 2 elements in the first dimension and 5 elements in the seccond dimension.

### What's the difference between shape and reshape?

The shape is a attribute and reshape is a function.



In [64]:
reshape_example = np.arange(0, 10).reshape(2, 5)
reshape_example

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
initial_array = np.arange(100)
reshaped_array = initial_array.reshape(4,25)

print(f'The num of dimensions of initial_array is: {initial_array.ndim}, and the num of dimensions of reshaped_array is: {reshaped_array.ndim}')

print(f'The shape of initial_array is: {initial_array.shape}, and the shape of reshaped_array is: {reshaped_array.shape}')

print(f'\nThe initial array is: {initial_array}\n\nThe reshaped array is: {reshaped_array}')


The num of dimensions of initial_array is: 1, and the num of dimensions of reshaped_array is: 2
The shape of initial_array is: (100,), and the shape of reshaped_array is: (4, 25)

The initial array is: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

The reshaped array is: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


Initial we had a array with 100 elements with one dimension. After reshape we still have a array with 100 elements but now with two dimensions.

The first parameter of reshape is the number of elements in the first dimension and the seccond parameter is the number of elements in the seccond dimension.

In [66]:
num_rows, num_cols = reshaped_array.shape

for i in range(num_rows):
    for j in range(num_cols):
        element = reshaped_array[i, j]
        print(f"Element at row {i}, column {j}: {element}")

Element at row 0, column 0: 0
Element at row 0, column 1: 1
Element at row 0, column 2: 2
Element at row 0, column 3: 3
Element at row 0, column 4: 4
Element at row 0, column 5: 5
Element at row 0, column 6: 6
Element at row 0, column 7: 7
Element at row 0, column 8: 8
Element at row 0, column 9: 9
Element at row 0, column 10: 10
Element at row 0, column 11: 11
Element at row 0, column 12: 12
Element at row 0, column 13: 13
Element at row 0, column 14: 14
Element at row 0, column 15: 15
Element at row 0, column 16: 16
Element at row 0, column 17: 17
Element at row 0, column 18: 18
Element at row 0, column 19: 19
Element at row 0, column 20: 20
Element at row 0, column 21: 21
Element at row 0, column 22: 22
Element at row 0, column 23: 23
Element at row 0, column 24: 24
Element at row 1, column 0: 25
Element at row 1, column 1: 26
Element at row 1, column 2: 27
Element at row 1, column 3: 28
Element at row 1, column 4: 29
Element at row 1, column 5: 30
Element at row 1, column 6: 31
Ele

Each row ends after 25 elements. Because 100/4 = 25.

It's possible for 2 or more dimensions. For example, ```np.arange(0, 100).reshape(2, 5, 10)``` changes the shape of an array with a range of numbers from 0 to 99 to a array with 2 elements in the first dimension, 5 elements in the seccond dimension and 10 elements in the third dimension.

In [67]:
initial_array = np.arange(100)
thirt_dimensional_shaped_array = initial_array.reshape(2, 5, 10)
print(f'The num of dimensions of initial_array is: {initial_array.ndim}, and the num of dimensions of thirt_dimensional_shaped_array is: {thirt_dimensional_shaped_array.ndim}')

The num of dimensions of initial_array is: 1, and the num of dimensions of thirt_dimensional_shaped_array is: 3


In [68]:
num_rows, num_cols, depth = thirt_dimensional_shaped_array.shape

for i in range(num_rows):
    for j in range(num_cols):
        for k in range(depth):
            element = thirt_dimensional_shaped_array[i, j, k]
            print(f"Element at row {i}, column {j}, depth {k}: {element}")

Element at row 0, column 0, depth 0: 0
Element at row 0, column 0, depth 1: 1
Element at row 0, column 0, depth 2: 2
Element at row 0, column 0, depth 3: 3
Element at row 0, column 0, depth 4: 4
Element at row 0, column 0, depth 5: 5
Element at row 0, column 0, depth 6: 6
Element at row 0, column 0, depth 7: 7
Element at row 0, column 0, depth 8: 8
Element at row 0, column 0, depth 9: 9
Element at row 0, column 1, depth 0: 10
Element at row 0, column 1, depth 1: 11
Element at row 0, column 1, depth 2: 12
Element at row 0, column 1, depth 3: 13
Element at row 0, column 1, depth 4: 14
Element at row 0, column 1, depth 5: 15
Element at row 0, column 1, depth 6: 16
Element at row 0, column 1, depth 7: 17
Element at row 0, column 1, depth 8: 18
Element at row 0, column 1, depth 9: 19
Element at row 0, column 2, depth 0: 20
Element at row 0, column 2, depth 1: 21
Element at row 0, column 2, depth 2: 22
Element at row 0, column 2, depth 3: 23
Element at row 0, column 2, depth 4: 24
Element at

### Slicing

#### What's slicing?

Slicing is a function to access a part of an array.

#### How to use slicing?

We can use slicing to access a part of an array. For example, ```np.arange(0, 10)[0:5]``` access the first 5 elements of an array with a range of numbers from 0 to 9.

The first parameter of slicing is the start index and the seccond parameter is the end index.

In [69]:
initial_array = np.arange(100)
example_slicing1 = initial_array[0:10]
example_slicing1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### More examples:

a[1:5] access the elements from index 1 to index 4. 5 is not included.

a[:5] access the elements from index 0 to index 4. 5 is not included.

a[1:] access the elements from index 1 to the last index.

a[::-1] access the elements from the last index to the first index.

a[::2] access the elements from the first index to the last index with a step of 2.

In [70]:
first_example = np.arange(0,10)[1:5]
seccond_example = np.arange(0,10)[:5]
third_example = np.arange(0,10)[1:]
fourth_example = np.arange(0,10)[::-1]
fifth_example = np.arange(0,10)[::2]

print(f' The first example is: {first_example}\n The seccond example is: {seccond_example}\n The third example is: {third_example}\n The fourth example is: {fourth_example}\n The fifth example is: {fifth_example}')

 The first example is: [1 2 3 4]
 The seccond example is: [0 1 2 3 4]
 The third example is: [1 2 3 4 5 6 7 8 9]
 The fourth example is: [9 8 7 6 5 4 3 2 1 0]
 The fifth example is: [0 2 4 6 8]


If we slice an array and assign it to a variable, the variable will be a view of the array. In other words, if we change the variable, the array will be changed too.

In [71]:
initial_array = np.arange(10)
slicing_array = initial_array[0:5]

slicing_array[0] = 1000

print(f'The initial array is: {initial_array}\nThe slicing array is: {slicing_array}')

The initial array is: [1000    1    2    3    4    5    6    7    8    9]
The slicing array is: [1000    1    2    3    4]


But we can use the function copy to create a copy of the array. In other words, if we change the variable, the array will not be changed.

In [72]:
initial_array = np.arange(10)
slicing_array = initial_array[0:5].copy()

slicing_array[0] = 1000

print(f'The initial array is: {initial_array}\nThe slicing array is: {slicing_array}')

The initial array is: [0 1 2 3 4 5 6 7 8 9]
The slicing array is: [1000    1    2    3    4]


#### Argwhere

#### What's argwhere?

argwhere is a function to return the indexes of the elements that are different from zero.

#### How to use argwhere?

We can use argwhere to return the indexes of the elements that are different from zero. For example, ```np.argwhere(np.arange(0, 10) > 5)``` returns the indexes of the elements that are greater than 5.

In [73]:
initial_array = np.arange(10)
idx1 = np.argwhere(initial_array == 5)
idx2 = np.argwhere(initial_array < 5)
idx3 = np.argwhere(initial_array > 5)

print(f'The value of idx1 is: {idx1}\n\nThe value of idx2 is: {idx2}\n\nThe value of idx3 is: {idx3}\n')

The value of idx1 is: [[5]]

The value of idx2 is: [[0]
 [1]
 [2]
 [3]
 [4]]

The value of idx3 is: [[6]
 [7]
 [8]
 [9]]



In [74]:
print(f'The dimension of idx1 is: {idx1.ndim}\nThe dimension of idx2 is: {idx2.ndim}\nThe dimension of idx3 is: {idx3.ndim}\n')

The dimension of idx1 is: 2
The dimension of idx2 is: 2
The dimension of idx3 is: 2



After we use the argwhere function we create an array of arrays. Each array contains the index of the element that is different from zero. In other ords now we have a 2 dimensional array.

In [75]:
idx1 = np.argwhere(initial_array == 5)[0][0]
idx2 = np.argwhere(initial_array < 5)[0][0]
idx3 = np.argwhere(initial_array > 5)[0][0]

print(f' The value of idx1 is: {idx1}\n The value of idx2 is: {idx2}\n The value of idx3 is: {idx3}')

 The value of idx1 is: 5
 The value of idx2 is: 0
 The value of idx3 is: 6


Now the result is a one dimensional array.

Now let's take a look at matrix.

In [76]:
matrix_one = np.array(np.arange(0, 10).reshape(2, 5))
print(f'The matrix is:\n {matrix_one}')

The matrix is:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


Slicing 2 dimensional array is similar to slicing 1 dimensional array. The difference is that we need to use 2 indexes.

The first index is the row and the seccond index is the column.


In [77]:
first_slice = matrix_one[0:1, 0:2]
second_slice = matrix_one[1:, 3:]
third_slice = matrix_one[:, 2:4]
fourth_slice = matrix_one[:, 2:3]
fifth_slice = matrix_one[:, 2]
sixth_slice = matrix_one[1, :]
seventh_slice = matrix_one[1, 2:3]
eighth_slice = matrix_one[1, 2]

print(f'The first slice is:\n {first_slice}\n\nThe second slice is:\n {second_slice}\n\nThe third slice is:\n {third_slice}\n\nThe fourth slice is:\n {fourth_slice}\n\nThe fifth slice is:\n {fifth_slice}\n\nThe sixth slice is:\n {sixth_slice}\n\nThe seventh slice is:\n {seventh_slice}\n\nThe eighth slice is:\n {eighth_slice}')

The first slice is:
 [[0 1]]

The second slice is:
 [[8 9]]

The third slice is:
 [[2 3]
 [7 8]]

The fourth slice is:
 [[2]
 [7]]

The fifth slice is:
 [2 7]

The sixth slice is:
 [5 6 7 8 9]

The seventh slice is:
 [7]

The eighth slice is:
 7


To transpose a matrix we use the attribute T.

In [78]:
transposed_matrix_one = matrix_one.T

print(f'The matrix one is:\n {matrix_one}\n\nThe transposed matrix one is:\n {transposed_matrix_one}')

The matrix one is:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

The transposed matrix one is:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


It's possible to generete a copy without using copy function.

In [79]:
original_array = np.arange(100)
copy_array = original_array[original_array < 50]
copy_array[0] = 1000

print(f'The original array is:\n {original_array}\n\nThe copy array is:\n {copy_array}')

The original array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

The copy array is:
 [1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49]


It's possible too using boolean operators.

In [80]:
copy_array = original_array[(original_array < 50) & (original_array > 40)]
print(copy_array)

[41 42 43 44 45 46 47 48 49]


What's the diference between & and and?

The difference is that & is a bitwise operator and and is a logical operator.

### What's the difference between bitwise operator and logical operator?

The difference is that bitwise operator works with bits and logical operator works with boolean values.

bitwise operatos | logical operators |
-----------------|-------------------|
&                | and               |
\|               | or                |
^                | xor               |
~                | not               |


In [81]:
matrix_one = np.round(np.random.rand(2,2) * 10)
matrix_one

array([[8., 9.],
       [8., 6.]])

In [82]:
matrix_one = matrix_one + 10
print(f'The matrix one after the addition is:\n {matrix_one}')

The matrix one after the addition is:
 [[18. 19.]
 [18. 16.]]


Look, we add 10 to each element of the array, without creating a new array.